/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootLayoutImport } from './routes/_rootLayout'
import { Route as AuthLayoutImport } from './routes/_authLayout'
import { Route as RootLayoutIndexImport } from './routes/_rootLayout/index'
import { Route as RootLayoutAdminImport } from './routes/_rootLayout/admin'
import { Route as AuthLayoutSignUpImport } from './routes/_authLayout/sign-up'
import { Route as AuthLayoutSignInImport } from './routes/_authLayout/sign-in'
import { Route as RootLayoutKudosSentImport } from './routes/_rootLayout/kudos/sent'
import { Route as RootLayoutKudosReceivedImport } from './routes/_rootLayout/kudos/received'
import { Route as RootLayoutAdminDashboardImport } from './routes/_rootLayout/admin/dashboard'

// Create/Update Routes

const RootLayoutRoute = RootLayoutImport.update({
  id: '/_rootLayout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRoute,
} as any)

const RootLayoutIndexRoute = RootLayoutIndexImport.update({
  path: '/',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutAdminRoute = RootLayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => RootLayoutRoute,
} as any)

const AuthLayoutSignUpRoute = AuthLayoutSignUpImport.update({
  path: '/sign-up',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutSignInRoute = AuthLayoutSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const RootLayoutKudosSentRoute = RootLayoutKudosSentImport.update({
  path: '/kudos/sent',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutKudosReceivedRoute = RootLayoutKudosReceivedImport.update({
  path: '/kudos/received',
  getParentRoute: () => RootLayoutRoute,
} as any)

const RootLayoutAdminDashboardRoute = RootLayoutAdminDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => RootLayoutAdminRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_rootLayout': {
      id: '/_rootLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/sign-in': {
      id: '/_authLayout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthLayoutSignInImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authLayout/sign-up': {
      id: '/_authLayout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthLayoutSignUpImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_rootLayout/admin': {
      id: '/_rootLayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof RootLayoutAdminImport
      parentRoute: typeof RootLayoutImport
    }
    '/_rootLayout/': {
      id: '/_rootLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RootLayoutIndexImport
      parentRoute: typeof RootLayoutImport
    }
    '/_rootLayout/admin/dashboard': {
      id: '/_rootLayout/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof RootLayoutAdminDashboardImport
      parentRoute: typeof RootLayoutAdminImport
    }
    '/_rootLayout/kudos/received': {
      id: '/_rootLayout/kudos/received'
      path: '/kudos/received'
      fullPath: '/kudos/received'
      preLoaderRoute: typeof RootLayoutKudosReceivedImport
      parentRoute: typeof RootLayoutImport
    }
    '/_rootLayout/kudos/sent': {
      id: '/_rootLayout/kudos/sent'
      path: '/kudos/sent'
      fullPath: '/kudos/sent'
      preLoaderRoute: typeof RootLayoutKudosSentImport
      parentRoute: typeof RootLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthLayoutRoute: AuthLayoutRoute.addChildren({
    AuthLayoutSignInRoute,
    AuthLayoutSignUpRoute,
  }),
  RootLayoutRoute: RootLayoutRoute.addChildren({
    RootLayoutAdminRoute: RootLayoutAdminRoute.addChildren({
      RootLayoutAdminDashboardRoute,
    }),
    RootLayoutIndexRoute,
    RootLayoutKudosReceivedRoute,
    RootLayoutKudosSentRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authLayout",
        "/_rootLayout"
      ]
    },
    "/_authLayout": {
      "filePath": "_authLayout.tsx",
      "children": [
        "/_authLayout/sign-in",
        "/_authLayout/sign-up"
      ]
    },
    "/_rootLayout": {
      "filePath": "_rootLayout.tsx",
      "children": [
        "/_rootLayout/admin",
        "/_rootLayout/",
        "/_rootLayout/kudos/received",
        "/_rootLayout/kudos/sent"
      ]
    },
    "/_authLayout/sign-in": {
      "filePath": "_authLayout/sign-in.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/sign-up": {
      "filePath": "_authLayout/sign-up.tsx",
      "parent": "/_authLayout"
    },
    "/_rootLayout/admin": {
      "filePath": "_rootLayout/admin.tsx",
      "parent": "/_rootLayout",
      "children": [
        "/_rootLayout/admin/dashboard"
      ]
    },
    "/_rootLayout/": {
      "filePath": "_rootLayout/index.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/admin/dashboard": {
      "filePath": "_rootLayout/admin/dashboard.tsx",
      "parent": "/_rootLayout/admin"
    },
    "/_rootLayout/kudos/received": {
      "filePath": "_rootLayout/kudos/received.tsx",
      "parent": "/_rootLayout"
    },
    "/_rootLayout/kudos/sent": {
      "filePath": "_rootLayout/kudos/sent.tsx",
      "parent": "/_rootLayout"
    }
  }
}
ROUTE_MANIFEST_END */
